version: '3.8'
services:
  airflow:
    container_name: AIRFLOW_Project
    build: .
    restart: unless-stopped
    command: standalone
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    env_file:
      - .env
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./include:/usr/local/airflow/include
      - ./data:/usr/local/airflow/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: AIRFLOW_Project_postgres
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-postgres}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: